version: 2.1
jobs:
  setup:
    docker:
      - image: python:3.7.3-stretch # Use the same Docker base as the project
    steps:
      - checkout      
      - run:
          name: create virtual environment
          command: |
            make setup
      - run:
          name: install dependencies
          command: |
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run:
          name: run lint
          command: |
            . ~/.venv/bin/activate
            make lint
  build_docker:
    working_directory: /app
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker
          command: |
            sh run_docker.sh
      - run:
          name: push docker container
          command: |
            sh update_docker.sh
workflows:
  default:
    jobs:
      - setup
      - build_docker:
          requires: [setup]