version: 2.1

orbs: 
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@1.3

commands:
  install_eksctl:
    description: Install eksctl
    steps:
      - run:
          name: Install eksctl
          command: |
            PLATFORM=$(uname -s)_amd64
            curl -sLO "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
            tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
            sudo mv /tmp/eksctl /usr/local/bin

jobs:
  setup:
    docker:
      - image: python:3.7.3-stretch # Use the same Docker base as the project
    steps:
      - checkout      
      - run:
          name: create virtual environment
          command: |
            make setup
      - run:
          name: install dependencies
          command: |
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run:
          name: run lint
          command: |
            . ~/.venv/bin/activate
            make lint
  build_docker:
    working_directory: /app
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker
          command: |
            sh run_docker.sh
      - run:
          name: push docker container
          command: |
            sh upload_docker.sh

  create-cluster:
    executor: aws-eks/python3
    steps:
      - checkout
      - install_eksctl  
      - run:
          name: Create AWS EKS Cluster
          command: |    
            eksctl create cluster \
              --name 05-capstone-${CIRCLE_WORKFLOW_ID:0:7} \
              --region ${AWS_DEFAULT_REGION}
              --zones us-east-1a,us-east-1b,us-east-1c,us-east-1d
workflows:
  default:
    jobs:
      - setup
      - build_docker:
          requires: [setup]
      - create-cluster:
          requires: [build_docker]